### ISSUE TITLE
Tests Fail At ls_se

### ISSUE THREAD

**Issue by hoganman** [t2k-software/t2kdm#28]
After I configure, the tests fail at ls_se with "Permission denied"

```bash
[mhogan@hep dirac_ui]$ t2kdm-config 

Configuration parameter: blacklist

Blacklist storage elements from being used automatically.
They can still be specified explicitly.
Provide the list as whitespace-separated list of SE names.
Example: UKI-LT2-QMUL2-disk UKI-NORTHGRID-SHEF-HEP-disk

Current value: -
Default value: -

Enter new value [keep current]: 

Configuration parameter: maid_config

Where the configuration file for the `t2kdm-maid` command is stored.
If you do not deal with raw data replication, don't worry about it.


Current value: /home/mhogan/.config/t2kdm/maid.conf
Default value: /home/mhogan/.config/t2kdm/maid.conf

Enter new value [keep current]: 

Configuration parameter: basedir

What base directory should be assumed for all files on the grid?

Current value: /t2k.org
Default value: /t2k.org

Enter new value [keep current]: 

Configuration parameter: location

What is your location?
This is used to determine the closest storage element when downloading files.
Must follow the general pattern of '/continent/country/site'.
Examples: /europe/uk/ral
          /americas/ca/triumf
          /asia/jp/kek
You can see the locations of all available SEs by running `t2kdm-SEs`.

Current value: /americas/ca/triumf
Default value: /

Enter new value [keep current]: 

Configuration parameter: backend

Which backend should be used?
Supported backends: dirac, gfal, lcg

Current value: dirac
Default value: dirac

Enter new value [keep current]: 
Saving configuration in /home/mhogan/.config/t2kdm/t2kdm.conf
[mhogan@hep dirac_ui]$ t2kdm-tests 
Testing ls...
Testing ls_se...
Traceback (most recent call last):
  File "/home/mhogan/software/dirac_ui/Linux_x86_64_glibc-2.12/bin/t2kdm-tests", line 10, in <module>
    sys.exit(run_tests())
  File "/home/mhogan/software/dirac_ui/Linux_x86_64_glibc-2.12/lib/python2.7/site-packages/t2kdm/tests.py", line 245, in run_tests
    run_read_only_tests()
  File "/home/mhogan/software/dirac_ui/Linux_x86_64_glibc-2.12/lib/python2.7/site-packages/t2kdm/tests.py", line 64, in run_read_only_tests
    entries = t2kdm.backend.ls_se(testdir, se=testSEs[0])
  File "/home/mhogan/software/dirac_ui/Linux_x86_64_glibc-2.12/lib/python2.7/site-packages/t2kdm/backends.py", line 118, in ls_se
    return self._ls_se(surl, **kwargs)
  File "/home/mhogan/software/dirac_ui/Linux_x86_64_glibc-2.12/lib/python2.7/site-packages/t2kdm/backends.py", line 903, in _ls_se
    raise BackendException(e.stderr)
t2kdm.backends.BackendException: gfal-ls error: 13 (Permission denied) - srm-ifce err: Permission denied, err: [SE][Ls][SRM_AUTHORIZATION_FAILURE] httpg://heplnx204.pp.rl.ac.uk:8443/srm/managerv2: login failed

```

**Comment by ast0815** [comment]
Do you have a proper dirac proxy? What does `dirac-proxy-info` tell you?

**Comment by hoganman** [comment]
I think I had a bad proxy somehow. I destroyed my previous one and initialized a new one. 
```bash
subject      : /DC=org/DC=opensciencegrid/O=Open Science Grid/OU=People/CN=Matthew Hogan 4143/CN=64656701/CN=3833284473
issuer       : /DC=org/DC=opensciencegrid/O=Open Science Grid/OU=People/CN=Matthew Hogan 4143/CN=64656701
identity     : /DC=org/DC=opensciencegrid/O=Open Science Grid/OU=People/CN=Matthew Hogan 4143
timeleft     : 18:04:02
DIRAC group  : t2k.org_user
rfc          : True
path         : /tmp/x509up_u500
username     : matthew.hogan
properties   : NormalUser, JobMonitor
VOMS         : True
VOMS fqan    : ['/t2k.org']
```

The ```t2kdm-tests``` appears to work now

```bash
[mhogan@hep dirac_ui]$ t2kdm-tests 
Testing ls...
Testing ls_se...
Testing is_dir...
Testing is_dir_se...
Testing replicas...
Testing exists...
Testing checksum...
Testing state...
Testing StorageElement...
Testing get...
Testing check...
Testing Commands...
Testing CLI...
All done.
```
